### ISSUE TITLE
API Beschränken

### ISSUE THREAD

**Issue by Metzograf** [DieSchittigs/contao-content-api-bundle#15]
Ich versuche wie in der Readme geschrieben den Zugriff auf die API zu begrenzen. Leider funktioniert das bei mir nicht. Sie wird nicht in meinen Response Header übernommen. Ich möchte das die API ausschließlich von einer anderen bestimmten Domain aufgerufen werden darf.

In meiner app/config/parameters.yml steht:
```
# This file has been auto-generated during installation
parameters:
    database_host: XXX
    database_port: XXX
    database_user: XXX
    database_password: XXX
    database_name: XXX
    secret: XXX
    content_api_enabled: true
    content_api_headers:
     "Access-Control-Allow-Origin": "https://mysite.de"
    

# Contao configuration 
contao: 
    url_suffix: ''  
```
